/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id: dot3StatsTable_data_set.h,v 1.1.1.1 2013/09/04 04:14:30 rtlac Exp $
 */
#ifndef DOT3STATSTABLE_DATA_SET_H
#define DOT3STATSTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */


#ifdef __cplusplus
}
#endif
#endif                          /* DOT3STATSTABLE_DATA_SET_H */
