/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IPTIMEROUTER_H
#define IPTIMEROUTER_H

/* function declarations */
void init_ipTimeRouter(void);
Netsnmp_Node_Handler handle_Manufacturer;
Netsnmp_Node_Handler handle_Model;
Netsnmp_Node_Handler handle_Version;
Netsnmp_Node_Handler handle_ifNumber;
Netsnmp_Node_Handler handle_essNumber;
Netsnmp_Node_Handler handle_LanMac;
Netsnmp_Node_Handler handle_WanMac;
Netsnmp_Node_Handler handle_PrimaryDNS;
Netsnmp_Node_Handler handle_SecondayDNS;
Netsnmp_Node_Handler handle_RemoteAccess;
Netsnmp_Node_Handler handle_RemoteAccessPort;
Netsnmp_Node_Handler handle_UpgradeStart;
Netsnmp_Node_Handler handle_Reboot;

#endif /* IPTIMEROUTER_H */
