/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ROUTERWIRELESS_H
#define ROUTERWIRELESS_H

/* function declarations */
void init_routerWireless(void);
void initialize_table_essTable(void);
Netsnmp_Node_Handler handle_essNumber;
Netsnmp_Node_Handler essTable_handler;
Netsnmp_First_Data_Point  essTable_get_first_data_point;
Netsnmp_Next_Data_Point   essTable_get_next_data_point;
NetsnmpCacheLoad essTable_load;
NetsnmpCacheFree essTable_free;
#define ESSTABLE_TIMEOUT  60

/* column number definitions for table essTable */
       #define COLUMN_ESSINDEX		1
       #define COLUMN_ESSSSID		2
       #define COLUMN_ESSSSIDBROADCAST		3
       #define COLUMN_ESSMODE		4
       #define COLUMN_ESSSECURITYSET		5
       #define COLUMN_ESSSECURITYKEY		6
       #define COLUMN_ESS8021XRADIUSIPADDRESS		7
       #define COLUMN_ESS8021XRADIUSKEY		8
       #define COLUMN_ESS8021XRADIUSPORT		9
       #define COLUMN_ESSCHANNELINFO		10
#endif /* ROUTERWIRELESS_H */
