/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "routerInformation.h"

/** Initializes the routerInformation module */
void
init_routerInformation(void)
{
    const oid Manufacturer_oid[] = { 1,3,6,1,4,1,12874,1,1,1 };
    const oid Model_oid[] = { 1,3,6,1,4,1,12874,1,1,2 };
    const oid Version_oid[] = { 1,3,6,1,4,1,12874,1,1,3 };

  DEBUGMSGTL(("routerInformation", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("Manufacturer", handle_Manufacturer,
                               Manufacturer_oid, OID_LENGTH(Manufacturer_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("Model", handle_Model,
                               Model_oid, OID_LENGTH(Model_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("Version", handle_Version,
                               Version_oid, OID_LENGTH(Version_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_Manufacturer(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    char getbuf[245] = "EFM networks";
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, getbuf, strlen(getbuf));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_Manufacturer\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_Model(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    char getbuf[245] = "";
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            hwinfo_get_product_name(getbuf);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, getbuf, strlen(getbuf));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_Model\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_Version(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    char getbuf[245] = "";
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            get_firmware_version(getbuf);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, getbuf, strlen(getbuf));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_Version\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
