/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ROUTERSYSTEM_H
#define ROUTERSYSTEM_H

/* function declarations */
void init_routerSystem(void);
Netsnmp_Node_Handler handle_LanMac;
Netsnmp_Node_Handler handle_WanMac;
Netsnmp_Node_Handler handle_PrimaryDNS;
Netsnmp_Node_Handler handle_SecondayDNS;
Netsnmp_Node_Handler handle_RemoteAccess;
Netsnmp_Node_Handler handle_RemoteAccessPort;
Netsnmp_Node_Handler handle_UpgradeUrl;
Netsnmp_Node_Handler handle_UpgradeStart;
Netsnmp_Node_Handler handle_Reboot;

#endif /* ROUTERSYSTEM_H */
