/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "routerWireless.h"

#include <lib/snmp_iptime.h>

/** Initializes the routerWireless module */
void
init_routerWireless(void)
{
    const oid essNumber_oid[] = { 1,3,6,1,4,1,12874,1,4,1 };

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("essNumber", handle_essNumber,
                               essNumber_oid, OID_LENGTH(essNumber_oid),
                               HANDLER_CAN_RONLY
        ));

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_essTable();
}

//  # Determine the first/last column names

/** Initialize the essTable table by defining its contents and how it's structured */
void
initialize_table_essTable(void)
{
    const oid essTable_oid[] = {1,3,6,1,4,1,12874,1,4,2};
    const size_t essTable_oid_len   = OID_LENGTH(essTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("routerWireless:init", "initializing table essTable\n"));

    reg = netsnmp_create_handler_registration(
              "essTable",     essTable_handler,
              essTable_oid, essTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: idx_essIndex */
                           0);
    table_info->min_column = COLUMN_ESSINDEX;
    table_info->max_column = COLUMN_ESSCHANNELINFO;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = essTable_get_first_data_point;
    iinfo->get_next_data_point  = essTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator2( reg, iinfo );
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(ESSTABLE_TIMEOUT,
                                  essTable_load, essTable_free,
                                  essTable_oid, essTable_oid_len),
            NULL /*TABLE_ITERATOR_NAME*/);

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct essTable_entry {
    /* Index values */
    long idx_essIndex;

    /* Column values */
    long essIndex;
    char essSsid[128];
    size_t essSsid_len;
    char old_essSsid[128];
    size_t old_essSsid_len;
    long essSsidBroadcast;
    long old_essSsidBroadcast;
    long essMode;
    long essSecuritySet;
    long old_essSecuritySet;
    char essSecurityKey[128];
    size_t essSecurityKey_len;
    char old_essSecurityKey[128];
    size_t old_essSecurityKey_len;
    in_addr_t ess8021xRadiusIPaddress;
    in_addr_t old_ess8021xRadiusIPaddress;
    char ess8021xRadiusKey[128];
    size_t ess8021xRadiusKey_len;
    char old_ess8021xRadiusKey[128];
    size_t old_ess8021xRadiusKey_len;
    long ess8021xRadiusPort;
    long old_ess8021xRadiusPort;
    long essChannelInfo;
    long old_essChannelInfo;

    /* Illustrate using a simple linked list */
    int   valid;
    struct essTable_entry *next;
};

struct essTable_entry  *essTable_head;

/* create a new row in the (unsorted) table */
struct essTable_entry *
essTable_createEntry(
                 long  essIndex,
                 essTable *ess_table
                ) {
    struct essTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct essTable_entry);
    if (!entry)
        return NULL;

    entry->idx_essIndex = essIndex;

    entry->essIndex = essIndex;
    strcpy(entry->essSsid, ess_table->ssid);
    entry->essSsid_len = strlen(ess_table->ssid);
    entry->essSsidBroadcast = ess_table->ssid_broadcast;
    entry->essMode = ess_table->mode;
    entry->essSecuritySet = ess_table->security_set;
    strcpy(entry->essSecurityKey, ess_table->security_key);
    entry->essSecurityKey_len = strlen(ess_table->security_key);
    entry->ess8021xRadiusIPaddress = inet_addr(ess_table->radius_ip);
    strcpy(entry->ess8021xRadiusKey, ess_table->radius_key);
    entry->ess8021xRadiusKey_len = strlen(ess_table->radius_key);
    entry->ess8021xRadiusPort = ess_table->radius_port;
    entry->essChannelInfo = ess_table->channel;

    entry->next = essTable_head;
    essTable_head = entry;

    return entry;
}

/* remove a row from the table */
void
essTable_removeEntry( struct essTable_entry *entry ) {
    struct essTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = essTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        essTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

static int
wireless_createEntry(int *idx, int mode)
{
        essTable ess_table[MAX_ESS_NUM_PER_MODE];
        int bssnum, i;

        bssnum = wireless_get_all_ess_entry(mode, ess_table);
        for (i=0; i<bssnum; i++, (*idx)++)
                essTable_createEntry(*idx+1, &ess_table[i]);

        return bssnum;
}

/* Example cache handling - set up linked list from a suitable file */
int
essTable_load( netsnmp_cache *cache, void *vmagic ) {
	int idx = 0;

	essTable_free(cache, NULL);

	wireless_createEntry(&idx, WIRELESS_MODE_24G);
	wireless_createEntry(&idx, WIRELESS_MODE_5G);

	return 0;  /* OK */
}

void
essTable_free( netsnmp_cache *cache, void *vmagic ) {
    struct essTable_entry *this, *that;

    for ( this = essTable_head; this; this=that ) {
        that = this->next;
        SNMP_FREE( this );   /* XXX - release any other internal resources */
    }
    essTable_head = NULL;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
essTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    if (essTable_head == NULL)
        return NULL;

    *my_loop_context = essTable_head;
    return essTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
essTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct essTable_entry *entry = (struct essTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->idx_essIndex );
        idx = idx->next_variable;

        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the essTable table */
int
essTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct essTable_entry          *table_entry;
    int ret;

    DEBUGMSGTL(("routerWireless:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct essTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ESSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->essIndex);
                break;
            case COLUMN_ESSSSID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->essSsid,
                                          table_entry->essSsid_len);
                break;
            case COLUMN_ESSSSIDBROADCAST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->essSsidBroadcast);
                break;
            case COLUMN_ESSMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->essMode);
                break;
            case COLUMN_ESSSECURITYSET:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->essSecuritySet);
                break;
            case COLUMN_ESSSECURITYKEY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->essSecurityKey,
                                          table_entry->essSecurityKey_len);
                break;
            case COLUMN_ESS8021XRADIUSIPADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                          table_entry->ess8021xRadiusIPaddress);
                break;
            case COLUMN_ESS8021XRADIUSKEY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ess8021xRadiusKey,
                                          table_entry->ess8021xRadiusKey_len);
                break;
            case COLUMN_ESS8021XRADIUSPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ess8021xRadiusPort);
                break;
            case COLUMN_ESSCHANNELINFO:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->essChannelInfo);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct essTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ESSSSID:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->essSsid));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESSSSIDBROADCAST:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESSSECURITYSET:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESSSECURITYKEY:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->essSecurityKey));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESS8021XRADIUSIPADDRESS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESS8021XRADIUSKEY:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->ess8021xRadiusKey));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESS8021XRADIUSPORT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ESSCHANNELINFO:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct essTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ESSSSID:
                memcpy( table_entry->old_essSsid,
                        table_entry->essSsid,
                        sizeof(table_entry->essSsid));
                table_entry->old_essSsid_len =
                        table_entry->essSsid_len;
                memset( table_entry->essSsid, 0,
                        sizeof(table_entry->essSsid));
                memcpy( table_entry->essSsid,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->essSsid_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ESSSSIDBROADCAST:
                table_entry->old_essSsidBroadcast = table_entry->essSsidBroadcast;
                table_entry->essSsidBroadcast     = *request->requestvb->val.integer;
                break;
            case COLUMN_ESSSECURITYSET:
                table_entry->old_essSecuritySet = table_entry->essSecuritySet;
                table_entry->essSecuritySet     = *request->requestvb->val.integer;
                break;
            case COLUMN_ESSSECURITYKEY:
                memcpy( table_entry->old_essSecurityKey,
                        table_entry->essSecurityKey,
                        sizeof(table_entry->essSecurityKey));
                table_entry->old_essSecurityKey_len =
                        table_entry->essSecurityKey_len;
                memset( table_entry->essSecurityKey, 0,
                        sizeof(table_entry->essSecurityKey));
                memcpy( table_entry->essSecurityKey,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->essSecurityKey_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ESS8021XRADIUSIPADDRESS:
                table_entry->old_ess8021xRadiusIPaddress = table_entry->ess8021xRadiusIPaddress;
                table_entry->ess8021xRadiusIPaddress     = *request->requestvb->val.integer;
                break;
            case COLUMN_ESS8021XRADIUSKEY:
                memcpy( table_entry->old_ess8021xRadiusKey,
                        table_entry->ess8021xRadiusKey,
                        sizeof(table_entry->ess8021xRadiusKey));
                table_entry->old_ess8021xRadiusKey_len =
                        table_entry->ess8021xRadiusKey_len;
                memset( table_entry->ess8021xRadiusKey, 0,
                        sizeof(table_entry->ess8021xRadiusKey));
                memcpy( table_entry->ess8021xRadiusKey,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->ess8021xRadiusKey_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ESS8021XRADIUSPORT:
                table_entry->old_ess8021xRadiusPort = table_entry->ess8021xRadiusPort;
                table_entry->ess8021xRadiusPort     = *request->requestvb->val.integer;
                break;
            case COLUMN_ESSCHANNELINFO:
                table_entry->old_essChannelInfo = table_entry->essChannelInfo;
                table_entry->essChannelInfo     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct essTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ESSSSID:
                memcpy( table_entry->essSsid,
                        table_entry->old_essSsid,
                        sizeof(table_entry->essSsid));
                memset( table_entry->old_essSsid, 0,
                        sizeof(table_entry->essSsid));
                table_entry->essSsid_len =
                        table_entry->old_essSsid_len;
                break;
            case COLUMN_ESSSSIDBROADCAST:
                table_entry->essSsidBroadcast     = table_entry->old_essSsidBroadcast;
                table_entry->old_essSsidBroadcast = 0;
                break;
            case COLUMN_ESSSECURITYSET:
                table_entry->essSecuritySet     = table_entry->old_essSecuritySet;
                table_entry->old_essSecuritySet = 0;
                break;
            case COLUMN_ESSSECURITYKEY:
                memcpy( table_entry->essSecurityKey,
                        table_entry->old_essSecurityKey,
                        sizeof(table_entry->essSecurityKey));
                memset( table_entry->old_essSecurityKey, 0,
                        sizeof(table_entry->essSecurityKey));
                table_entry->essSecurityKey_len =
                        table_entry->old_essSecurityKey_len;
                break;
            case COLUMN_ESS8021XRADIUSIPADDRESS:
                table_entry->ess8021xRadiusIPaddress     = table_entry->old_ess8021xRadiusIPaddress;
                table_entry->old_ess8021xRadiusIPaddress = 0;
                break;
            case COLUMN_ESS8021XRADIUSKEY:
                memcpy( table_entry->ess8021xRadiusKey,
                        table_entry->old_ess8021xRadiusKey,
                        sizeof(table_entry->ess8021xRadiusKey));
                memset( table_entry->old_ess8021xRadiusKey, 0,
                        sizeof(table_entry->ess8021xRadiusKey));
                table_entry->ess8021xRadiusKey_len =
                        table_entry->old_ess8021xRadiusKey_len;
                break;
            case COLUMN_ESS8021XRADIUSPORT:
                table_entry->ess8021xRadiusPort     = table_entry->old_ess8021xRadiusPort;
                table_entry->old_ess8021xRadiusPort = 0;
                break;
            case COLUMN_ESSCHANNELINFO:
                table_entry->essChannelInfo     = table_entry->old_essChannelInfo;
                table_entry->old_essChannelInfo = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
handle_essNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int essnum = 0;
    /* We are never called for a GETNEXT if it's registered as a
      "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            essnum = wireless_get_mbss_count(WIRELESS_MODE_24G);
            essnum += wireless_get_mbss_count(WIRELESS_MODE_5G);

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &essnum, sizeof(essnum));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_essNumber\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

