/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ROUTERINFORMATION_H
#define ROUTERINFORMATION_H

/* function declarations */
void init_routerInformation(void);
Netsnmp_Node_Handler handle_Manufacturer;
Netsnmp_Node_Handler handle_Model;
Netsnmp_Node_Handler handle_Version;

#endif /* ROUTERINFORMATION_H */
