/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ROUTERADDRESSTBL_H
#define ROUTERADDRESSTBL_H

/* function declarations */
void init_routerAddressTbl(void);
void initialize_table_addressTable(void);
Netsnmp_Node_Handler addressTable_handler;
Netsnmp_First_Data_Point  addressTable_get_first_data_point;
Netsnmp_Next_Data_Point   addressTable_get_next_data_point;
NetsnmpCacheLoad addressTable_load;
NetsnmpCacheFree addressTable_free;
#define ADDRESSTABLE_TIMEOUT  60

#define MAX_MAC_ADDR_LEN 32

/* column number definitions for table addressTable */
       #define COLUMN_ATIFDESCR		1
       #define COLUMN_ATPHYSADDRESS		2
       #define COLUMN_ATIPADDRESS		3
#endif /* ROUTERADDRESSTBL_H */
