/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "routerInterface.h"

#include <lib/snmp_iptime.h>

/** Initializes the routerInterface module */
void
init_routerInterface(void)
{
    const oid ifNumber_oid[] = { 1,3,6,1,4,1,12874,1,2,1 };

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ifaceNumber", handle_ifNumber,
                               ifNumber_oid, OID_LENGTH(ifNumber_oid),
                               HANDLER_CAN_RONLY
        ));

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_interfaceTable();
}

//  # Determine the first/last column names

/** Initialize the ifTable table by defining its contents and how it's structured */
void
initialize_table_interfaceTable(void)
{
    const oid ifTable_oid[] = {1,3,6,1,4,1,12874,1,2,2};
    const size_t ifTable_oid_len   = OID_LENGTH(ifTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("routerInterface:init", "initializing table ifTable\n"));

    reg = netsnmp_create_handler_registration(
              "ifaceTable",     ifTable_handler,
              ifTable_oid, ifTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: idx_ifIndex */
                           0);
    table_info->min_column = COLUMN_IFINDEX;
    table_info->max_column = COLUMN_IFSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = ifTable_get_first_data_point;
    iinfo->get_next_data_point  = ifTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator2( reg, iinfo );
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(IFTABLE_TIMEOUT,
                                  ifTable_load, ifTable_free,
                                  ifTable_oid, ifTable_oid_len),
            NULL /*TABLE_ITERATOR_NAME*/);

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct ifTable_entry {
    /* Index values */
    long idx_ifIndex;

    /* Column values */
    long ifIndex;
    char ifDescr[256];
    size_t ifDescr_len;
    long ifMode;
    long ifStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct ifTable_entry *next;
};

struct ifTable_entry  *ifTable_head;

/* create a new row in the (unsorted) table */
struct ifTable_entry *
ifTable_createEntry(
                 long  ifIndex,
                 char  *ifDescr,
                 long  ifMode,
                 long  ifStatus
                ) {
    struct ifTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct ifTable_entry);
    if (!entry)
        return NULL;

    entry->idx_ifIndex = ifIndex;

    entry->ifIndex = ifIndex;
    strcpy(entry->ifDescr, ifDescr);
    entry->ifDescr_len = strlen(ifDescr);
    entry->ifMode = ifMode;
    entry->ifStatus = ifStatus;

    entry->next = ifTable_head;
    ifTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
ifTable_removeEntry( struct ifTable_entry *entry ) {
    struct ifTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = ifTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        ifTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

static int
ethernet_createEntry(int *idx)
{
	char buf[STRMAX];
	int portnum, i, status;

	portnum = hwinfo_get_num_maxport();
	for (i= 0; i<portnum; i++, (*idx)++)
	{
		if (i== 0) strcpy(buf, "WAN");
		else sprintf(buf, "LAN%d", i);

         	status = get_port_link_status(i);
		ifTable_createEntry(*idx+1, buf, IFTYPE_ETHERNET, status);
	}

	return portnum;
}

static int
wireless_createEntry(int *idx, int mode)
{
	essTable ess_table[MAX_ESS_NUM_PER_MODE];
	int bssnum, i, status;

	bssnum = wireless_get_all_ess_entry(mode, ess_table);
	for (i=0; i<bssnum; i++, (*idx)++)
	{
		status = (ess_table[0].run == 0) ? 0 : ess_table[i].run;
		ifTable_createEntry(
			*idx+1, 
			ess_table[i].ssid, 
			(mode==WIRELESS_MODE_24G)?IFTYPE_WL24G:IFTYPE_WL5G, 
			status);
	}

	return bssnum;
}

/* Example cache handling - set up linked list from a suitable file */
int
ifTable_load( netsnmp_cache *cache, void *vmagic ) {
	int idx = 0;

	ifTable_free(cache, NULL);

	ethernet_createEntry(&idx);
	wireless_createEntry(&idx, WIRELESS_MODE_24G);
	wireless_createEntry(&idx, WIRELESS_MODE_5G);

	return 0;  /* OK */
}

void
ifTable_free( netsnmp_cache *cache, void *vmagic ) {
    struct ifTable_entry *this, *that;

    for ( this = ifTable_head; this; this=that ) {
        that = this->next;
        SNMP_FREE( this );   /* XXX - release any other internal resources */
    }
    ifTable_head = NULL;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
ifTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    if (ifTable_head == NULL)
        return NULL;

    *my_loop_context = ifTable_head;
    return ifTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
ifTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct ifTable_entry *entry = (struct ifTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->idx_ifIndex );

        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the ifTable table */
int
ifTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct ifTable_entry          *table_entry;

    DEBUGMSGTL(("routerInterface:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ifTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_IFINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ifIndex);
                break;
            case COLUMN_IFDESCR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ifDescr,
                                          table_entry->ifDescr_len);
                break;
            case COLUMN_IFTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ifMode);
                break;
            case COLUMN_IFSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ifStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}

int
handle_ifNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
   int ifnum = 0;

    /* We are never called for a GETNEXT if it's registered as a
      "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            ifnum = hwinfo_get_num_maxport();
            ifnum += wireless_get_mbss_count(WIRELESS_MODE_24G);
            ifnum += wireless_get_mbss_count(WIRELESS_MODE_5G);

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &ifnum, sizeof(ifnum));
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ifNumber\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

