/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ROUTERINTERFACE_H
#define ROUTERINTERFACE_H

/* function declarations */
void init_routerInterface(void);
void initialize_table_interfaceTable(void);
Netsnmp_Node_Handler handle_ifNumber;
Netsnmp_Node_Handler ifTable_handler;
Netsnmp_First_Data_Point  ifTable_get_first_data_point;
Netsnmp_Next_Data_Point   ifTable_get_next_data_point;
NetsnmpCacheLoad ifTable_load;
NetsnmpCacheFree ifTable_free;
#define IFTABLE_TIMEOUT  60

/* column number definitions for table ifTable */
       #define COLUMN_IFINDEX		1
       #define COLUMN_IFDESCR		2
       #define COLUMN_IFTYPE		3
       #define COLUMN_IFSTATUS          4

#endif /* ROUTERINTERFACE_H */
